name: Release Build

on:
    release:
        types: [created]

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.21'

            - name: Build Multi-Platform Binaries
              run: |
                  platforms=("windows/amd64" "windows/386" "linux/amd64" "linux/386" "darwin/amd64" "darwin/arm64")
                  for platform in "${platforms[@]}"
                  do
                    platform_split=(${platform//\// })
                    GOOS=${platform_split[0]}
                    GOARCH=${platform_split[1]}
                    output_name=gitsyncer-$GOOS-$GOARCH
                    if [ $GOOS = "windows" ]; then
                      output_name+='.exe'
                    fi
                    
                    echo "Building for $GOOS/$GOARCH"
                    GOOS=$GOOS GOARCH=$GOARCH go build -o build/$output_name
                  done

            - name: Upload Release Assets
              run: |
                  cd build
                  for file in *; do
                    gh release upload ${{ github.event.release.tag_name }} "$file"
                  done
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
